version: '3'

services:
  nginx:
    image: nginx:1.15.8-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
      - ./nginx/log:/var/log/nginx/
      - ./nginx/ssl:/etc/nginx/ssl/
    links:
      - node
    # networks:
    #   - docker-network
  
  node:
    image: node:10.13-alpine
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/home/node/app
    ports:
      - 3000:3000
    command: sh -c "npm install --silent && npm start"
    # networks:
    #   - docker-network

# networks:
#   docker-network:
#     driver: bridge